name: Test on Android
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start emulator
        run: |
          # Define variables
          SDK_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
          SDK_DIR="$HOME/Android/Sdk"
          TOOLS_DIR="$SDK_DIR/cmdline-tools"
          TOOLS_BIN="$TOOLS_DIR/latest/bin"
          EMULATORS_BIN="$SDK_DIR/emulator"
          PLATFORM_TOOLS_BIN="$SDK_DIR/platform-tools"
          AVD_NAME="test_emulator"

          # Step 1: Download Android command line tools
          mkdir -p "$SDK_DIR"
          echo "Downloading Android command line tools..."
          curl -o "$SDK_DIR/cmdline-tools.zip" -L "$SDK_URL"

          # Step 2: Unzip the command line tools
          mkdir -p "$TOOLS_DIR"
          unzip -qo "$SDK_DIR/cmdline-tools.zip" -d "$TOOLS_DIR"
          mv "$TOOLS_DIR/cmdline-tools" "$TOOLS_DIR/latest"
          rm "$SDK_DIR/cmdline-tools.zip"

          # Step 3: Setup environment variables
          export PATH="$TOOLS_BIN:$EMULATORS_BIN:$PLATFORM_TOOLS_BIN:$PATH"
          export ANDROID_HOME=~/Android/Sdk/
          export ANDROID_AVD_HOME=~/.android/avd/

          # Step 4: Accept licenses and install required packages
          mkdir -p "$SDK_DIR/licenses"
          echo "Installing SDK packages..."
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "system-images;android-29;google_apis;x86_64" "emulator"

          # Step 5: Create and start an emulator
          echo "Creating Android Virtual Device (AVD)..."
          mkdir -p "$ANDROID_AVD_HOME"
          avdmanager create avd --name "$AVD_NAME" --package "system-images;android-29;google_apis;x86_64" --device "pixel" --abi google_apis/x86_64 --force

          # Step 6: Launch the emulator
          echo "Launching emulator..."
          emulator -avd "$AVD_NAME" -no-snapshot -no-window -noaudio -no-boot-anim -accel on -memory 4096 -netdelay none -netspeed full &

          # Print success message
          echo "Android SDK setup complete. Emulator is running."

          # Add binaries to GITHUB_PATH
          echo $TOOLS_DIR >> $GITHUB_PATH
          echo $EMULATORS_BIN >> $GITHUB_PATH
          echo $PLATFORM_TOOLS_BIN >> $GITHUB_PATH

          # Add to GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_AVD_HOME=$ANDROID_AVD_HOME" >> $GITHUB_ENV

      - name: Setup VS Code dark mode settings
        run: |
          mkdir -p ~/.vscode-server/data/Machine
          echo '{"workbench.colorTheme": "Default Dark Modern"}' > ~/.vscode-server/data/Machine/settings.json
      - uses: fawazahmed0/action-debug-vscode@v3
