name: autocommit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: add file
        run: |
          echo foo > test.txt
          git add test.txt
          git commit -m "add a test file"
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
