name: Test on Cygwin
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: cygwin/cygwin-install-action@v5
        with:
          add-to-path: false
      - uses: fawazahmed0/action-debug-vscode@v3
