name: Test on FreeBSD
on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        default: x86_64
      release:
        required: true
        type: string
        default: 15.0
jobs:
  test:
    runs-on: ${{ inputs.arch == 'x86_64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    steps:
      - name: Start VM
        id: vm
        uses: vmactions/freebsd-vm@v1
        with:
          sync: nfs
          arch: ${{ inputs.arch }}
          release: ${{ inputs.release }}
      - uses: fawazahmed0/action-debug-vscode@v3
