name: Test on FreeBSD
on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        default: x86_64
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start VM
        id: vm
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          sync: sshfs
          arch: ${{ inputs.arch }}
      - uses: fawazahmed0/action-debug@main
