name: gstreamer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Build
        run: |
          pip3 install meson
          wget https://gitlab.freedesktop.org/gstreamer/gstreamer/-/archive/1.22.6/gstreamer-1.22.6.tar.gz
          tar -xf gstreamer-1.22.6.tar.gz
          cd gstreamer-1.22.6
          meson setup builddir
          meson compile -C builddir
          tar -czf ../builddir.tar.gz builddir

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builddir
          path: ./builddir.tar.gz
