name: Test on IBM
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: bjia56/ibm-powervs-action@main
        with:
          ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
          prefix: 'experiments-${{ github.run_number }}'
      - shell: powervs {0}
        run: |
          export PATH=/opt/freeware/bin:$PATH
          chfs -a size=+1G /var
          chfs -a size=+2G /opt
          dnf install -y git gcc gcc-c++
      - name: Setup VS Code dark mode settings
        run: |
          mkdir -p ~/.vscode-server/data/Machine
          echo '{"workbench.colorTheme": "Default Dark Modern"}' > ~/.vscode-server/data/Machine/settings.json
      - uses: fawazahmed0/action-debug-vscode@v3
