name: Test Scrypted on MacOS
on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        default: x86_64
jobs:
  test:
    runs-on: ${{ inputs.arch == 'x86_64' && 'macos-13' || 'macos-14' }}
    
    steps:
      - name: Install scrypted server
        uses: scryptedapp/setup-scrypted@v0.0.2
        with:
          version: beta

      - name: Run establish a cf tunnel
        uses: vmactions/cf-tunnel@v0
        with:
          protocol: http
          port: 11080

      - name: Wait to exit
        shell: bash
        run: |
          while [ ! -f ./continue ]; do sleep 5; done
