name: Test on MacOS
on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        default: x86_64
jobs:
  test:
    runs-on: ${{ inputs.arch == 'x86_64' && 'macos-13' || 'macos-14' }}
    steps:
      - name: Setup VS Code dark mode settings
        run: |
          mkdir -p ~/.vscode-server/data/Machine
          echo '{"workbench.colorTheme": "Default Dark Modern"}' > ~/.vscode-server/data/Machine/settings.json
      - uses: fawazahmed0/action-debug-vscode@v3
