name: Test Scrypted on MacOS arm64
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-14
    
    steps:
      - name: Install scrypted server
        uses: scryptedapp/setup-scrypted@v0.0.2

      - name: Run establish a cf tunnel
        uses: vmactions/cf-tunnel@v0
        with:
          protocol: tcp
          port: 10443

      - uses: fawazahmed0/action-debug@main
