name: Test on MacOS PPC
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 7200
    steps:
      - uses: bjia56/custom-actions/macppc-vm@main

      - uses: fawazahmed0/action-debug-vscode@v3
