name: Test on MidnightBSD
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: bjia56/midnightbsd-vm@main
      - uses: fawazahmed0/action-debug-vscode@v3
