name: Test on OmniOS
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start VM
        id: vm
        uses: vmactions/omnios-vm@v1
        with:
          sync: nfs
      - name: Setup VS Code dark mode settings
        run: |
          mkdir -p ~/.vscode-server/data/Machine
          echo '{"workbench.colorTheme": "Default Dark Modern"}' > ~/.vscode-server/data/Machine/settings.json
      - uses: fawazahmed0/action-debug-vscode@v3
