name: Test on OmniOS
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start VM
        id: vm
        uses: vmactions/omnios-vm@v1
        with:
          sync: nfs
      - uses: fawazahmed0/action-debug-vscode@v3
