name: Test on OpenBSD
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start VM
        id: vm
        uses: vmactions/openbsd-vm@v1
        with:
          sync: sshfs
      - uses: fawazahmed0/action-debug@main
