name: Test on OpenBSD
on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        default: x86_64
      release:
        required: true
        type: string
        default: 7.6
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start VM
        id: vm
        uses: vmactions/openbsd-vm@v1
        with:
          sync: nfs
          arch: ${{ inputs.arch }}
          release: ${{ inputs.release }}
      - uses: fawazahmed0/action-debug@main
