name: Test on Solaris
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start VM
        id: vm
        uses: vmactions/solaris-vm@v1
        with:
          sync: nfs
          prepare: |
            pkg install --accept cmake gcc git
      - uses: fawazahmed0/action-debug-vscode@v3
