name: Test on Solaris
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start VM
        id: vm
        uses: bjia56/solaris-vm@nfs
        with:
          sync: nfs
      - uses: fawazahmed0/action-debug@main
