name: Test on Ubuntu with compilers
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - name: Set up cosmocc
        uses: bjia56/setup-cosmocc@v0.0.3
        with:
          version: 3.6.0
      - uses: fawazahmed0/action-debug@main
