name: Test on Windows
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          mkdir -p ~/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          cd $HOME/.local/bin
          curl -L -o wget https://cosmo.zip/pub/cosmos/bin/wget
          curl -L -o zip https://cosmo.zip/pub/cosmos/bin/zip
          curl -L -o unzip https://cosmo.zip/pub/cosmos/bin/unzip
      - uses: microsoft/setup-msbuild@v2
      - uses: cygwin/cygwin-install-action@v5
        with:
          add-to-path: false
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
      - uses: fawazahmed0/action-debug-vscode@v3
