name: Test Scrypted on Windows
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-2019
    
    steps:
      - name: Install WSL
        run: |
          wsl.exe --update --web-download

      - name: Install WSL
        uses: Vampire/setup-wsl@v3

      - name: Install scrypted server
        uses: scryptedapp/setup-scrypted@v0.0.2

      - name: Run establish a cf tunnel
        uses: bjia56/cf-tunnel@win-fixes
        with:
          protocol: http
          port: 11080

      - uses: fawazahmed0/action-debug@main
      - name: Wait to exit
        if: false
        shell: bash
        run: |
          while [ ! -f ./continue ]; do sleep 5; done
