name: Test on Windows
on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        default: x86_64
      cygwin_arch:
        required: true
        type: string
        default: x86_64
jobs:
  test:
    runs-on: ${{ inputs.arch == 'x86_64' && 'windows-latest' || 'windows-11-arm' }}
    steps:
      - shell: bash
        if: ${{ inputs.arch == 'x86_64' }}
        run: |
          mkdir -p ~/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          cd $HOME/.local/bin
          curl -L -o wget https://cosmo.zip/pub/cosmos/bin/wget
          curl -L -o zip https://cosmo.zip/pub/cosmos/bin/zip
          curl -L -o unzip https://cosmo.zip/pub/cosmos/bin/unzip
      - uses: microsoft/setup-msbuild@v2
        if: ${{ inputs.arch == 'x86_64' }}
      - uses: cygwin/cygwin-install-action@v5
        if: ${{ inputs.arch == 'x86_64' }}
        with:
          add-to-path: false
          platform: ${{ inputs.cygwin_arch }}
      - uses: msys2/setup-msys2@v2
        if: ${{ inputs.arch == 'x86_64' }}
        with:
          update: true
      - uses: fawazahmed0/action-debug-vscode@v3
