name: Test Scrypted on Windows
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    
    steps:
      - name: Install scrypted server
        uses: scryptedapp/setup-scrypted@v0.0.2

      - name: Run establish a cf tunnel
        uses: vmactions/cf-tunnel@v0
        with:
          protocol: http
          port: 11080

      - name: Wait to exit
        shell: bash
        run: |
          while [ ! -f ./continue ]; do sleep 5; done
